### ISSUE TITLE
Still some formating issues in 2.3.1

### ISSUE THREAD

**Issue by Ninoss123** [renpy/vscode-language-renpy#334] opened 2023-06-04 19:12 UTC
### Extension version

2.3.1

### Issue description

Conditional statements in menu: have a weird syntax highlight

Actual thing :
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/27156922/5523e8bb-bc75-4c8a-8b43-c235329c665c)

Should look like : 
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/27156922/4b022f77-0157-4e96-a89d-7f6201c8324e)

**Comment by duckdoom4** [comment] 2023-06-04 22:42
Hm, I checked those when I pushed 2.3.1.. Worked fine then. I'll have another look tomorrow, maybe I messed it up in my hasty fix

**Comment by Savage1969** [comment] 2023-06-04 22:50
@duckdoom4 

It's doing a similar thing with some tags within Style defines but only some tags such as:
`color`
`background`
`unscrollable`

or any tag that has a hyphen in it such as
`idle_color`
`drop_shadow_color`
etc.

**Comment by duckdoom4** [comment] 2023-06-04 22:54
> @duckdoom4 
> 
> It's doing a similar thing with some tags within Style defines but only some tags such as:
> `color`
> `background`
> `unscrollable`
> 
> or any tag that has a hyphen in it such as
> `idle_color`
> `drop_shadow_color`
> etc.

Would you be able to compile a list of style properties that are not highlighted properly and submit it as a seperate issue? That would be super helpful, then I can fix all of them in one go tomorrow :)

**Comment by Savage1969** [comment] 2023-06-04 22:59
> > @duckdoom4
> > It's doing a similar thing with some tags within Style defines but only some tags such as:
> > `color`
> > `background`
> > `unscrollable`
> > or any tag that has a hyphen in it such as
> > `idle_color`
> > `drop_shadow_color`
> > etc.
> 
> Would you be able to compile a list of style properties that are not highlighted properly and submit it as a seperate issue? That would be super helpful, then I can fix all of them in one go tomorrow :)

There's so many. I truly think if you open any larger project in v2.1.7 (last known version with no color issues) and any current build you'll quickly see all the differences... even Character variables have changed coloring in all themes. The current builds also broke "Better Comments" which I know many folks use (an extension that changes color of comments with certain symbols post the pound symbol "#" such as "#*", "#!", and "#?"... as well as TODO tags).

But I'll try to find them all... it's going to be a rather large list so I need to find time when not working on projects and on the clock..

**Comment by duckdoom4** [comment] 2023-06-04 23:10
Please do try out version 2.2.1 that was released just a couple of minutes ago. (Note: it's currently no different from 2.3.1.)

But this patched a lot of issues with atl and screen language missing highlighting

**Comment by Savage1969** [comment] 2023-06-05 00:18
> Please do try out version 2.2.1 that was released just a couple of minutes ago. (Note: it's currently no different from **pre-release** v2.3.1.)
> 
> But this patched a lot of issues with atl and screen language missing highlighting.
> 
> Thanks in advance for your efforts :). I'll try to grab some larger open source project from GitHub somewhere (if I can find one)

Apologies, I should have noted that the issues are in v2.3.1 and didn't here, I did in the other issue #332 though.

**Comment by drdrr** [comment] 2023-06-06 04:07
Yeah, after the plugin was updated, I also noticed that tags and variables are not properly formatted.

In older 2.0.16:
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/78471758/51b64a21-70ba-448b-8d3d-37934612c378)

In 2.2.1 and 2.3.0:
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/78471758/c777016d-9908-4004-81ad-aa9b85637796)

**Comment by duckdoom4** [comment] 2023-06-06 05:44
> Yeah, after the plugin was updated, I also noticed that tags and variables are not properly formatted.
> 
> In older 2.0.16:
> ![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/78471758/51b64a21-70ba-448b-8d3d-37934612c378)
> 
> In 2.2.1 and 2.3.1:
> ![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/78471758/c777016d-9908-4004-81ad-aa9b85637796)
> 

In this case the updated syntax is actually properly highlighted. The tags are now individually colored and the placeholders are parsed as python expressions instead of a simple tag. I do see that your theme does give the same color to tags as variables, so you might want to add a color rule for that

**Comment by drdrr** [comment] 2023-06-06 06:24
> > Yeah, after the plugin was updated, I also noticed that tags and variables are not properly formatted.
> > In older 2.0.16:
> > ![image](https://user-images.githubusercontent.com/78471758/243542927-51b64a21-70ba-448b-8d3d-37934612c378.png)
> > In 2.2.1 and 2.3.1:
> > ![image](https://user-images.githubusercontent.com/78471758/243543030-c777016d-9908-4004-81ad-aa9b85637796.png)
> 
> In this case the updated syntax is actually properly highlighted. The tags are now individually colored and the placeholders are parsed as python expressions instead of a simple tag. I do see that your theme does give the same color to tags as variables and doesn't highlight punctuation in a different color than the string, so you might want to add a color rule for that.
> 
> As an example of a theme that does support it, have a look at the image in issue #328
> 
> What is the theme you are using?

Thanks! I'm using Atom One Dark. And One Dark Pro too. I noticed using the default theme Default Dark Modern, the brackets do highlighted differently. Will try to customize a little
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/78471758/24c9419a-ea71-42d0-93a7-29c2bae53380)

**Comment by duckdoom4** [comment] 2023-06-06 07:37
I'll have a look at the scopes used by that theme. Maybe I can introduce some fallback scopes

**Comment by Savage1969** [comment] 2023-06-06 13:30
@duckdoom4 note that many use One Dark Pro as well for your testing.

Also (and the reason I write), would you consider making a special v2.1.7 build with the text tag fixes so we have something stable to work with until this is all sorted? v2.1.7 was the last known build that projects all functioned correctly regardless of folder structure and SDK usage. This would be a great help to those of us that are using the product daily, it's quite crippling right now with the static data build not functioning correctly, etc. 

Thank you for your consideration and we all sincerely appreciate all your time and efforts.

**Comment by duckdoom4** [comment] 2023-06-06 14:09
@Savage1969  I'd love to help out and fix all the issues on your current project, but to do this I will need your help since I'm not having the same issues you seem to be facing. Could you please post screenshots of specific parts of your code that are incorrectly highlighted?

> init 1 screen xxxx
Yes, that's a statement that was indeed missing. I'll implement it right now and will let you know when you can install the new update.

> would you consider making a special v2.1.7 build
The current build is based on v2.1.7 with some minor changes, so I'd rather just fix the issue(s). When you go back to that version, does the static data building work as expected?

**Comment by duckdoom4** [comment] 2023-06-08 16:00
Hi all, please try 2.3.3. I added highlighting for the style statement and it's properties. 
I think that should fix most of these issues.

There is still screen language that I have to properly tackle. It's kinda hacked in right now to get it somehwat working

**Comment by Savage1969** [comment] 2023-06-09 22:05
2.3.3 still broken. For testing simply open any RenPy native "tutorial" 's game folder and look at text tags, styles, etc. This way you aren't dependent folks to provide specific pic examples of private projects.

Some other oddities that weren't in 2.1.7: 
- Comments made after anything seem to be triggered by the colon ` : `and anything afterwards is colored by any theme as non-commented code. Use `style whatever: # whatever "\n{=something}something:{/=something}{=something}{size=-2}{color=#333333}"` as an example candidate in your own testing rpy.
- Text tags are still wonky when in an `init python` initialization container. Use `variable = "[var]{b}{i}[_O0O0]{/i}{/b}{size=-12}txt{/size} v[var.tmp][var]"` as an example candidate in your own testing rpy. Another example candidate being less complex is `var = "{color=#C6C6C6}Txt{/color}"`
- There are more but this should hopefully provide a bit more insight.

Here's an image that gives a visual of the above random examples:
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/3585e5ff-ae42-4492-93d9-1dcaa63893f3)

**Comment by duckdoom4** [comment] 2023-06-10 06:19
> 2.3.3 still broken. For testing simply open any RenPy native "tutorial" 's game folder and look at text tags, styles, etc. This way you aren't dependent folks to provide specific pic examples of private projects.
> 
> Some other oddities that weren't in 2.1.7: 
> - Comments made after anything seem to be triggered by the colon ` : `and anything afterwards is colored by any theme as non-commented code. Use `style whatever: # whatever "\n{=something}something:{/=something}{=something}{size=-2}{color=#333333}"` as an example candidate in your own testing rpy.
> - Text tags are still wonky when in an `init python` initialization container. Use `variable = "[var]{b}{i}[_O0O0]{/i}{/b}{size=-12}txt{/size} v[var.tmp][var]"` as an example candidate in your own testing rpy. Another example candidate being less complex is `var = "{color=#C6C6C6}Txt{/color}"`
> - There are more but this should hopefully provide a bit more insight.
> 
> Here's an image that gives a visual of the above random examples:
> ![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/3585e5ff-ae42-4492-93d9-1dcaa63893f3)
> 
> 

Well the problem is that renpy language is rather large and that there are a lot of tiny interactions that could trigger an issue. We have a very large test file that covers a lot of these examples, but as you can see even that's not always enough. That's why I need to ask others to confirm everything is working as intended.

Other than that, thanks for these examples. I'll implement a fix for these today :)

**Comment by Savage1969** [comment] 2023-06-12 18:44
Some other issues in v2.3.3 that work fine when reverting back to v2.1.7 :

Editor: Color Decorators no longer work (uncomented or commented. Also I believe because they don't work commented is probably the reason why some extensions such as "Better Comments" no longer work as well.

Examples in v2.1.7
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/6040ace7-050f-4f51-8192-023d4f86ff2d)

Examples in v2.3.3
![image](https://github.com/LuqueDaniel/vscode-language-renpy/assets/108280960/1cf03bfe-f7b1-4b5f-9d84-6a5766dc2ebf)

**Comment by Savage1969** [comment] 2023-06-14 00:29
> @duckdoom4,
> 
> Some other issues in v2.3.3 that work fine when reverting back to v2.1.7 :
> ...

The above post's issues are corrected via v2.3.4

**Comment by duckdoom4** [comment] 2024-07-29 06:53
This was caused by the extension crashing. Should be fixed now

**Closed by duckdoom4** 2024-07-29 06:53 UTC
Labels: bug, topic:syntax
