### ISSUE TITLE
[Bug] - Extension alters workspace.settings.json with incorrect settings

### ISSUE THREAD

**Issue by Tristimdorion** [renpy/vscode-language-renpy#340] opened 2023-06-12 10:19 UTC
When installing the latest pre-release the workspace settings for 'Colors' create faulty settings with garbled data.

**Comment by duckdoom4** [comment] 2023-06-13 21:10
Please try v2.3.4, this issue is likely fixed in that build :)

**Comment by Tristimdorion** [comment] 2023-06-14 05:46
Can confirm issue is resolved with v2.3.4

**Comment by Tristimdorion** [comment] 2023-06-14 12:26
Unfortunately it is back, here is an overview of the faulty settings in my workspace:

				{
					"scope": "renpy.meta.color.#ffff00",
					"settings": {
						"foreground": "#ffff00"
					}
				},
				{
					"scope": "renpy.meta.color.ff0000",
					"settings": {
						"foreground": "ff0000"
					}
				},
				{
					"scope": "renpy.meta.color.ff0000}{size=18}[distraction_percentages[2]]%% chance{/size}{/color}\":",
					"settings": {
						"foreground": "ff0000}{size=18}[distraction_percentages[2]]%% chance{/size}{/color}\":"
					}
				},
				{
					"scope": "renpy.meta.color.ff0000}{size=18}[distraction_percentages[1]]%% chance{/size}{/color}\":",
					"settings": {
						"foreground": "ff0000}{size=18}[distraction_percentages[1]]%% chance{/size}{/color}\":"
					}
				},
				{
					"scope": "renpy.meta.color.ff0000}{size=18}[distraction_percentages[0]]%% chance{/size}{/color}\":",
					"settings": {
						"foreground": "ff0000}{size=18}[distraction_percentages[0]]%% chance{/size}{/color}\":"
					}
				}

**Comment by duckdoom4** [comment] 2023-06-14 17:01
Okay, so I resolved this issue however I'm a little surprised.
The issue is that `{color=ff0000}` doesn't contain a `#`. According to the renpy documentation this is invalid syntax. Does it actually compile and work as intended?

**Comment by Tristimdorion** [comment] 2023-06-16 14:13
It really does work, it just renders as if the # was there.

**Comment by duckdoom4** [comment] 2023-06-16 22:27
Hm, okay. In that case I'll have to add support for that

**Closed** 2024-08-15 22:14 UTC
